@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Modulo *-right-> "1" UniqueModuleList
UniqueModuleList o-right-> Module

Module "1" *-down-> "*" Event
Event "1" *-down-> "*" Deadline
@enduml
