@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
    package Command {
        Class "{abstract}\nCommand" as Command
        Class EditCommand
    }
    package Parser {
        Interface Parser <<Interface>>
        Class EditCommandParser
    }
}

EditCommand -up-|>Command
EditCommandParser .up.|> Parser

@enduml
