@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Package Logic{
Class HiddenLogic #FFFFFF
}

Package Model <<Rectangle>>{
    Interface ReadOnlyModulo <<Interface>>
    Interface Model <<Interface>>
    Interface ObservableList <<Interface>>
    Class Modulo
    Class ReadOnlyModulo
    Class Model
    Class ModelManager
    Class UserPrefs
    Class ReadOnlyUserPrefs

    Package Displayable {
        Interface Displayable <<Interface>>
        Enum DisplayableType <<enumeration>>
        Class DisplayablePair

        DisplayablePair .up.|> Displayable
    }

    Package Event {
        Class Event
        Class PartialEvent
        Class Location
        Enum EventType <<enumeration>>
        Class UniqueEventList
    }

    Package Module {
        Class Module
        Class ModuleLibrary
        Class PartialModule
        Class ModuleCode
        Class AcademicYear
        Class UniqueModuleList
    }

    Package Deadline {
        Class Deadline
    }

    Class Name
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


Modulo .up.|> ReadOnlyModulo
ModelManager .up.|> Model
Model .up.> ObservableList
ModelManager .up> Displayable
ModelManager .up> DisplayableType
ModelManager o--> "1" Modulo
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs


Modulo *--> "1" UniqueModuleList
UniqueModuleList o--> "*" Module
Module *--> Name
Module *--> AcademicYear
Module *--> ModuleCode
PartialModule -up-|> Module
ModuleLibrary .down.> Module
ModuleLibrary .left.> Logic
Module "1" *-left-> "*" Event
Module .up|> Displayable

Modulo *--> "1" UniqueEventList
UniqueEventList o--> "*" Event
Event *--> Name
Event *--> Location
Event .up|> Displayable
PartialEvent -up-|> Event
Event --> EventType
Event "1" *-left-> "*" Deadline

Deadline *-right-> Name
Deadline .up.|> Displayable



ModuleCode -[hidden]right-> AcademicYear
AcademicYear -[hidden]down-> Name
EventType -[hidden]down-> Deadline

ModelManager -->"1" Module : filtered list
ModelManager -->"1" Event : filtered list
@enduml
