@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "a:AddModuleCommand" as AddModuleCommand LOGIC_COLOR
participant "result:AddModuleCommandResult" as AddModuleCommandResult LOGIC_COLOR
participant ":AddModuleStatefulLogicManager" as AddModuleStatefulLogicManager LOGIC_COLOR
end box

activate AddModuleCommand
activate LogicManager

create AddModuleCommandResult
AddModuleCommand -> AddModuleCommandResult
activate AddModuleCommandResult

AddModuleCommandResult --> AddModuleCommand
deactivate AddModuleCommandResult

group State Loading
AddModuleCommand --> LogicManager : result
deactivate AddModuleCommand

opt result instanceof AddModuleCommandResult
LogicManager -> AddModuleStatefulLogicManager: setStateWithCommandResult(result)
activate AddModuleStatefulLogicManager
AddModuleStatefulLogicManager --> LogicManager
deactivate AddModuleStatefulLogicManager

end
end

[<--LogicManager
deactivate AddModuleStatefulLogicManager
deactivate LogicManager
@enduml
