@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModuloParser" as ModuloParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedModulo" as VersionedModulo MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ModuloParser : parseCommand(undo)
activate ModuloParser

create UndoCommand
ModuloParser -> UndoCommand
activate UndoCommand

UndoCommand --> ModuloParser
deactivate UndoCommand

ModuloParser --> LogicManager : u
deactivate ModuloParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoModulo()
activate Model

Model -> VersionedModulo : undo()
activate VersionedModulo

VersionedModulo -> VersionedModulo :resetData(ReadOnlyModulo)
VersionedModulo --> Model :
deactivate VersionedModulo

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
